[package]
name = "checkpoint-table"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
clap = { version = "4.5", features = ["derive"] }
common = { path = "../common" }
delta_kernel = { path = "../../../kernel", features = [
  "default-engine-rustls",
] }
env_logger = "0.11.8"
tokio = { version = "1.0", features = ["full"] }

# for cargo-release
[package.metadata.release]
release = false
