[package]
name = "s3-copy-atomic"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
clap = { version = "4.5", features = ["derive"] }
delta_kernel = { path = "../../", features = [
  "arrow",
  "default-engine-rustls",
  "internal-api",
] }
env_logger = "0.11.8"
object_store = { version = "0.12.3", features = ["aws", "azure", "gcp"] }
tokio = { version = "1.47", features = ["rt-multi-thread", "macros"] }
url = "2"

# for cargo-release
[package.metadata.release]
release = false
